package ru.iliavolkov.weather.utils

const val BUNDLE_KEY_MAIN_FRAGMENT_IN_DETAILS_FRAGMENT ="BUNDLE_KEY_MAIN_FRAGMENT_IN_DETAILS_FRAGMENT"
const val BUNDLE_KEY_MAIN_FRAGMENT_IN_DETAILS_FRAGMENT_POSITION ="BUNDLE_KEY_MAIN_FRAGMENT_IN_DETAILS_FRAGMENT_POSITION"
const val API_KEY_NAME = "X-Yandex-API-Key"
const val KEY_LAT = "KEY_LAT"
const val KEY_LON = "KEY_LON"
const val BUNDLE_KEY_WEATHER = "BUNDLE_KEY_WEATHER"
const val BROADCAST_ACTION = "BROADCAST_ACTION"
const val YANDEX_API_URL = "https://api.weather.yandex.ru/"
const val YANDEX_API_URL_END_POINT = "v2/informers"
const val DB_NAME = "History.db"
const val MIN_DISTANCE = 100f
const val REFRESH_PERIOD = 60000L
const val REQUEST_CODE = 999